
server:
  port: 7016

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: demo-svc
spring:
  application:
    name: boot3-micrometer-demo